name: Petio
services:
  app:
    image: 	ghcr.io/petio-team/petio@sha256:41b9f0a5618fd7f82173cb576a1f9694ff90e4e1ddf2ae90eb4095ffccabf84e
    restart: unless-stopped
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use.
      volumes:
        - container: /config
          description:
            en_us: Contains the config file.
        - container: /data
          description:
            en_us: Contains the petio data.
      ports:
        - container: '7777'
          description:
            en_us: WebUI Port
    ports:
      - target: 7777
        published: 7777
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/petio/config
        target: /config
      - type: bind
        source: /DATA/AppData/petio/data
        target: /data
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://docs.petio.tv/install-guides/docker'
  tagline:
    en_us: A third party companion app available to Plex server owners to allow their users to request, review and discover content.
  screenshot_link:
  developer: Petio Team
  author: WisdomSky
  icon: https://raw.githubusercontent.com/WisdomSky/Casaos-Appstore/main/Apps/Petio/icon.png
  thumbnail: https://raw.githubusercontent.com/WisdomSky/Casaos-Appstore/main/Apps/Petio/icon.png
  title:
    en_us: Petio
  tips:
    before_install:
        en_us: MongoDB is required when setting up Petio. Make sure to install it if you haven't installed it yet.
  category: Media
  port_map: '7777'
