name: MongoDB
services:
  app:
    image: mongo:6.0.6
    restart: unless-stopped
    network_mode: bridge
    networks:
      default:
        aliases:
          - mongo
    hostname: mongo
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ
    x-casaos:
      envs:
        - container: PUID
          description:
            en_us: for UserID
        - container: PGID
          description:
            en_us: for GroupID
        - container: TZ
          description:
            en_us: specify a timezone to use.
      volumes:
        - container: /data/configdb
          description:
            en_us: MongoDB Config
        - container: /data/db
          description:
            en_us: MongoDB Database file
      ports:
        - container: '27017'
          description:
            en_us: MongoDB Port
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/mongo/data/configdb
        target: /data/configdb
      - type: bind
        source: /DATA/AppData/mongo/data/db
        target: /data/db
x-casaos:
  architectures:
    - amd64
    - arm
    - arm64
  main: app
  description:
    en_us: 'Visit homepage: https://hub.docker.com/_/mongo'
  tagline:
    en_us: A free and open-source cross-platform document-oriented database program. Classified as a NoSQL database program, MongoDB uses JSON-like documents with schemata. 
  screenshot_link:
  developer: MongoDB Inc
  author: WisdomSky
  icon: https://raw.githubusercontent.com/WisdomSky/Casaos-Appstore/main/Apps/Mongo/icon.png
  thumbnail: https://raw.githubusercontent.com/WisdomSky/Casaos-Appstore/main/Apps/Mongo/icon.png
  title:
    en_us: MongoDB
  category: Database
  port_map: '27017'
